export type RegionalSystem = {
  code: string;
  name: string;
  connections: number;
  beneficiaries: number;
  province: string;
  commune: string;
  classification: string;
  generator: string;
  telemetry: string;
};

export const regionalSystems: RegionalSystem[] = [
  {
    "code": "SSR003018",
    "name": "COMITÉ DE AGUA POTABLE RURAL CHACAICO",
    "connections": 65,
    "beneficiaries": 201,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002110",
    "name": "COMITÉ DE AGUA POTABLE RURAL COLONIA MANUEL RODRÍGUEZ",
    "connections": 34,
    "beneficiaries": 105,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000982",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE ITRAQUE",
    "connections": 37,
    "beneficiaries": 114,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000981",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL PARQUE LOS ÁLAMOS",
    "connections": 150,
    "beneficiaries": 465,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002494",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUAQUÉN ALTO",
    "connections": 83,
    "beneficiaries": 257,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000983",
    "name": "COMITÉ DE AGUA POTABLE RURAL LOS CONFINES",
    "connections": 140,
    "beneficiaries": 434,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002044",
    "name": "COMITÉ DE AGUA POTABLE RURAL SANTA ELENA",
    "connections": 100,
    "beneficiaries": 310,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000992",
    "name": "COMITÉ DE AGUA POTABLE RURAL VILLA CHIHUAYHUE",
    "connections": 24,
    "beneficiaries": 74,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000980",
    "name": "COMITÉ DE AGUA POTABLE RURAL VILLA COYANCO",
    "connections": 61,
    "beneficiaries": 189,
    "province": "MALLECO",
    "commune": "ANGOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003016",
    "name": "COMITÉ DE AGUA POTABLE RURAL ALTO Y BAJO LONCOYAMO",
    "connections": 340,
    "beneficiaries": 1054,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000812",
    "name": "COMITÉ DE AGUA POTABLE RURAL CATRIPULLI",
    "connections": 83,
    "beneficiaries": 257,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003019",
    "name": "COMITÉ DE AGUA POTABLE RURAL CHAPO ROBLE RINCON",
    "connections": 194,
    "beneficiaries": 601,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002467",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE AGUA TENDIDA",
    "connections": 110,
    "beneficiaries": 341,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000810",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE AMULEY CULLINCO",
    "connections": 98,
    "beneficiaries": 303,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002466",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CAMAR",
    "connections": 165,
    "beneficiaries": 511,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000799",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE COI COI PILOLCURA CHAMPULLI",
    "connections": 43,
    "beneficiaries": 133,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003296",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE COLICO",
    "connections": 147,
    "beneficiaries": 455,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000801",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE NEHUENTÚE",
    "connections": 349,
    "beneficiaries": 1081,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000803",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PICHINGUAL",
    "connections": 84,
    "beneficiaries": 260,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000804",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PUYANGUI",
    "connections": 230,
    "beneficiaries": 713,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000808",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE RUCAHUE ALTO",
    "connections": 105,
    "beneficiaries": 325,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000800",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL COIHUE",
    "connections": 62,
    "beneficiaries": 192,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002149",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUEDAQUINTUE",
    "connections": 242,
    "beneficiaries": 750,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000811",
    "name": "COMITÉ DE AGUA POTABLE RURAL RINCONADA DE CULLINCO",
    "connections": 107,
    "beneficiaries": 331,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002465",
    "name": "COMITÉ DE AGUA POTABLE RURAL SECTOR CHAMPULLI",
    "connections": 238,
    "beneficiaries": 737,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000809",
    "name": "COMITÉ DE AGUA POTABLE RURAL SECTOR HUAPI TROVOLHUE",
    "connections": 183,
    "beneficiaries": 567,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000805",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRANA PUENTE",
    "connections": 100,
    "beneficiaries": 310,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000806",
    "name": "COMITÉ DE AGUA POTABLE RURAL Y ALCANTARILLADO RURAL DE TROVOLHUE",
    "connections": 928,
    "beneficiaries": 2876,
    "province": "CAUTÍN",
    "commune": "CARAHUE",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000813",
    "name": "COMITÉ DE AGUA POTABLE RURAL COIHUE PAINEMAL",
    "connections": 100,
    "beneficiaries": 310,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002162",
    "name": "COMITÉ DE AGUA POTABLE RURAL COMUNIDADES INDÍGENAS CARRERRIÑE-HUIÑOCO PICUTA",
    "connections": 225,
    "beneficiaries": 697,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002164",
    "name": "COMITÉ DE AGUA POTABLE RURAL CURACO, PITRACO, SANTA CAROLINA",
    "connections": 436,
    "beneficiaries": 1351,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002161",
    "name": "COMITÉ DE AGUA POTABLE RURAL CUYINCO MALALCHE",
    "connections": 596,
    "beneficiaries": 1847,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002468",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PIUHUICHEN",
    "connections": 100,
    "beneficiaries": 310,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000886",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE RAPAHUE",
    "connections": 106,
    "beneficiaries": 328,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000889",
    "name": "COMITÉ DE AGUA POTABLE RURAL DOLLINCO RUCAPANGUE",
    "connections": 185,
    "beneficiaries": 573,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000815",
    "name": "COMITÉ DE AGUA POTABLE RURAL J.J.J.A",
    "connections": 170,
    "beneficiaries": 527,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000887",
    "name": "COMITÉ DE AGUA POTABLE RURAL MEMBRILLO RINCÓN",
    "connections": 208,
    "beneficiaries": 644,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000888",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRANAHUILLIN",
    "connections": 330,
    "beneficiaries": 1023,
    "province": "CAUTÍN",
    "commune": "CHOLCHOL",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002495",
    "name": "COMITÉ DE AGUA POTABLE RURAL COMUNIDAD MIGUEL HUENTELÉN",
    "connections": 218,
    "beneficiaries": 675,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000985",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA CURACO",
    "connections": 110,
    "beneficiaries": 341,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000987",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL ENCINAR",
    "connections": 60,
    "beneficiaries": 186,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000990",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL SALTO DE CHANCAGUA",
    "connections": 44,
    "beneficiaries": 136,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000984",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUAPITRÍO",
    "connections": 276,
    "beneficiaries": 855,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003025",
    "name": "COMITÉ DE AGUA POTABLE RURAL JOSÉ MIGUEL CARRERA",
    "connections": 143,
    "beneficiaries": 443,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000988",
    "name": "COMITÉ DE AGUA POTABLE RURAL LA ESPERANZA",
    "connections": 160,
    "beneficiaries": 496,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002119",
    "name": "COMITÉ DE AGUA POTABLE RURAL LOLCURA SANTA LUISA",
    "connections": 141,
    "beneficiaries": 437,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000989",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUILQUIHUENCO",
    "connections": 140,
    "beneficiaries": 434,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000991",
    "name": "COMITÉ DE AGUA POTABLE RURAL SAN ANDRÉS RADAL",
    "connections": 82,
    "beneficiaries": 254,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000986",
    "name": "COMITÉ DE AGUA POTABLE RURAL VILLA RÍO AMARGO",
    "connections": 46,
    "beneficiaries": 142,
    "province": "MALLECO",
    "commune": "COLLIPULLI",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000817",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CHOROICO",
    "connections": 184,
    "beneficiaries": 570,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000820",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE LAS HORTENSIAS",
    "connections": 330,
    "beneficiaries": 1023,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000821",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE LOS LAURELES",
    "connections": 740,
    "beneficiaries": 2294,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000823",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA GARCÍA",
    "connections": 85,
    "beneficiaries": 263,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000818",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL ESFUERZO",
    "connections": 48,
    "beneficiaries": 148,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000103",
    "name": "COMITÉ DE AGUA POTABLE RURAL FAJA 12000 Y 14000 DE HUICHAHUE DE LA COMUNA DE CUNCO",
    "connections": 604,
    "beneficiaries": 1872,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002470",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUICHAHUE ALTO",
    "connections": 83,
    "beneficiaries": 257,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000819",
    "name": "COMITÉ DE AGUA POTABLE RURAL LA ESPERANZA",
    "connections": 110,
    "beneficiaries": 341,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002469",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUECHUREHUE",
    "connections": 649,
    "beneficiaries": 2011,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MAYOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000816",
    "name": "COMITÉ DE AGUA POTABLE RURAL SAN PEDRO",
    "connections": 176,
    "beneficiaries": 545,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000822",
    "name": "COMITÉ DE AGUA POTABLE RURAL UNIÓN CORDILLERA",
    "connections": 890,
    "beneficiaries": 2759,
    "province": "CAUTÍN",
    "commune": "CUNCO",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000993",
    "name": "COMITÉ DE AGUA POTABLE RURAL CORRETUÉ",
    "connections": 82,
    "beneficiaries": 254,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000995",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE MANZANAR",
    "connections": 143,
    "beneficiaries": 443,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000996",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE RARI RUCA",
    "connections": 83,
    "beneficiaries": 257,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000997",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE SANTA EMA",
    "connections": 148,
    "beneficiaries": 458,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000862",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE SANTA JULIA",
    "connections": 59,
    "beneficiaries": 182,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000999",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VEGA LARGA",
    "connections": 60,
    "beneficiaries": 186,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000994",
    "name": "COMITÉ DE AGUA POTABLE RURAL MALALCAHUELLO",
    "connections": 346,
    "beneficiaries": 1072,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003260",
    "name": "COMITÉ DE AGUA POTABLE RURAL RADALCO",
    "connections": 162,
    "beneficiaries": 502,
    "province": "MALLECO",
    "commune": "CURACAUTÍN",
    "classification": "MENOR",
    "generator": "S/I",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000824",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CATRIPULLI",
    "connections": 248,
    "beneficiaries": 768,
    "province": "CAUTÍN",
    "commune": "CURARREHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000825",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CURARREHUE",
    "connections": 777,
    "beneficiaries": 2408,
    "province": "CAUTÍN",
    "commune": "CURARREHUE",
    "classification": "MAYOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000827",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUENTE BASA CHICO PURRANQUE",
    "connections": 185,
    "beneficiaries": 573,
    "province": "CAUTÍN",
    "commune": "CURARREHUE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000003",
    "name": "COMITÉ DE AGUA POTABLE RURAL CANUTA CALBUQUEO",
    "connections": 59,
    "beneficiaries": 182,
    "province": "MALLECO",
    "commune": "ERCILLA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000004",
    "name": "COMITÉ DE AGUA POTABLE RURAL CHEQUENCO",
    "connections": 75,
    "beneficiaries": 232,
    "province": "MALLECO",
    "commune": "ERCILLA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000005",
    "name": "COMITÉ DE AGUA POTABLE RURAL COLLICO",
    "connections": 53,
    "beneficiaries": 164,
    "province": "MALLECO",
    "commune": "ERCILLA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000002",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CHACAICO",
    "connections": 65,
    "beneficiaries": 201,
    "province": "MALLECO",
    "commune": "ERCILLA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000006",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PAILAHUEQUE",
    "connections": 650,
    "beneficiaries": 2015,
    "province": "MALLECO",
    "commune": "ERCILLA",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000007",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PIDIMA",
    "connections": 170,
    "beneficiaries": 527,
    "province": "MALLECO",
    "commune": "ERCILLA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000828",
    "name": "COMITÉ DE AGUA POTABLE RURAL CALFUCO",
    "connections": 238,
    "beneficiaries": 737,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000834",
    "name": "COMITÉ DE AGUA POTABLE RURAL CHIHUIMPILLI",
    "connections": 91,
    "beneficiaries": 282,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000831",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE ALLIPÉN",
    "connections": 206,
    "beneficiaries": 638,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000833",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CAHUINPANGUE",
    "connections": 28,
    "beneficiaries": 86,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000835",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE COIPÚE",
    "connections": 120,
    "beneficiaries": 372,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000829",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CUICUICURA",
    "connections": 342,
    "beneficiaries": 1060,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000836",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE DOLLINCO QUEPE",
    "connections": 400,
    "beneficiaries": 1240,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000837",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE HACIENDA ALLIPÉN",
    "connections": 56,
    "beneficiaries": 173,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000838",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE HUILIO",
    "connections": 93,
    "beneficiaries": 288,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002129",
    "name": "COMITÉ DE AGUA POTABLE RURAL MAHUIDACHE",
    "connections": 511,
    "beneficiaries": 1584,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000843",
    "name": "COMITÉ DE AGUA POTABLE RURAL MARTÍNEZ DE ROZAS",
    "connections": 194,
    "beneficiaries": 601,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000830",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUQUEREO",
    "connections": 360,
    "beneficiaries": 1116,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000840",
    "name": "COMITÉ DE AGUA POTABLE RURAL RADAL",
    "connections": 439,
    "beneficiaries": 1360,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000832",
    "name": "COMITÉ DE AGUA POTABLE RURAL SÍNICO",
    "connections": 53,
    "beneficiaries": 164,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000842",
    "name": "COMITÉ DE AGUA POTABLE RURAL TUMUNTUCO DE TEMUNTUCO",
    "connections": 190,
    "beneficiaries": 589,
    "province": "CAUTÍN",
    "commune": "FREIRE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000847",
    "name": "COMITÉ DE AGUA POTABLE RURAL AILLINCO HUEQUEMAHUIDA",
    "connections": 70,
    "beneficiaries": 217,
    "province": "CAUTÍN",
    "commune": "GALVARINO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002152",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRAWEN KO",
    "connections": 198,
    "beneficiaries": 613,
    "province": "CAUTÍN",
    "commune": "GALVARINO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000848",
    "name": "COMITÉ DE AGUA POTABLE RURAL VILLA COIHUECO",
    "connections": 64,
    "beneficiaries": 198,
    "province": "CAUTÍN",
    "commune": "GALVARINO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000849",
    "name": "COMITÉ DE AGUA POTABLE RURAL VILLA EL CAPRICHO",
    "connections": 46,
    "beneficiaries": 142,
    "province": "CAUTÍN",
    "commune": "GALVARINO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002471",
    "name": "COMITÉ DE AGUA POTABLE RURAL BOTACURA",
    "connections": 88,
    "beneficiaries": 272,
    "province": "CAUTÍN",
    "commune": "GORBEA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000916",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUELLANTO BAJO",
    "connections": 311,
    "beneficiaries": 964,
    "province": "CAUTÍN",
    "commune": "GORBEA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003268",
    "name": "COMITÉ DE AGUA POTABLE RURAL SANTA JUANA LOS ACACIOS",
    "connections": 91,
    "beneficiaries": 282,
    "province": "CAUTÍN",
    "commune": "GORBEA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000860",
    "name": "COMITÉ DE AGUA POTABLE RURAL AGUA SANTA",
    "connections": 197,
    "beneficiaries": 610,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000853",
    "name": "COMITÉ DE AGUA POTABLE RURAL ANTINAO PAILLAL",
    "connections": 40,
    "beneficiaries": 124,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003017",
    "name": "COMITÉ DE AGUA POTABLE RURAL APR CENTRAL ALHUECO",
    "connections": 406,
    "beneficiaries": 1258,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002474",
    "name": "COMITÉ DE AGUA POTABLE RURAL BLANCO LEPÍN",
    "connections": 365,
    "beneficiaries": 1131,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003299",
    "name": "COMITÉ DE AGUA POTABLE RURAL CALLE DEL MEDIO SECTOR LOS TEMOS",
    "connections": 348,
    "beneficiaries": 1078,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000854",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE COLLÍN",
    "connections": 46,
    "beneficiaries": 142,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000857",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE MALPICHAHUE",
    "connections": 155,
    "beneficiaries": 480,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000855",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL ESCUDO",
    "connections": 48,
    "beneficiaries": 148,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000859",
    "name": "COMITÉ DE AGUA POTABLE RURAL LA COLONIA",
    "connections": 154,
    "beneficiaries": 477,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000856",
    "name": "COMITÉ DE AGUA POTABLE RURAL LAS MINAS",
    "connections": 23,
    "beneficiaries": 71,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003027",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLIULLIUCURA",
    "connections": 219,
    "beneficiaries": 678,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000858",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUMALAL CUNCO CHICO",
    "connections": 327,
    "beneficiaries": 1013,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002112",
    "name": "COMITÉ DE AGUA POTABLE RURAL SAN JUAN DE DOLLINCO Y CATRICURA",
    "connections": 191,
    "beneficiaries": 592,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002113",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRES ESQUINAS, LOS AROMOS, LA PEÑA NALCACO Y CHUMIL",
    "connections": 644,
    "beneficiaries": 1996,
    "province": "CAUTÍN",
    "commune": "LAUTARO",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000864",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CASAHUE",
    "connections": 58,
    "beneficiaries": 179,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000865",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE DONGUIL HUELLANTO",
    "connections": 89,
    "beneficiaries": 275,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000866",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE HUISCAPI",
    "connections": 664,
    "beneficiaries": 2058,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000867",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE LA PAZ",
    "connections": 380,
    "beneficiaries": 1178,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000868",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PAYA",
    "connections": 108,
    "beneficiaries": 334,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000851",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL PRADO",
    "connections": 41,
    "beneficiaries": 127,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000863",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUAQUI",
    "connections": 240,
    "beneficiaries": 744,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002476",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLIU LLIU SÉPTIMA FAJA",
    "connections": 180,
    "beneficiaries": 558,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002475",
    "name": "COMITÉ DE AGUA POTABLE RURAL MUQUÉN",
    "connections": 171,
    "beneficiaries": 530,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002140",
    "name": "COMITÉ DE AGUA POTABLE RURAL ÑUBLE",
    "connections": 219,
    "beneficiaries": 678,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000869",
    "name": "COMITÉ DE AGUA POTABLE RURAL SAN RAMÓN",
    "connections": 273,
    "beneficiaries": 846,
    "province": "CAUTÍN",
    "commune": "LONCOCHE",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000011",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE LIUCURA",
    "connections": 65,
    "beneficiaries": 201,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000013",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PEDREGOSO",
    "connections": 53,
    "beneficiaries": 164,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000014",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE SIERRA NEVADA",
    "connections": 42,
    "beneficiaries": 130,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000015",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE TROYO",
    "connections": 133,
    "beneficiaries": 412,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000009",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL NARANJO",
    "connections": 60,
    "beneficiaries": 186,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000010",
    "name": "COMITÉ DE AGUA POTABLE RURAL ICALMA",
    "connections": 102,
    "beneficiaries": 316,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000012",
    "name": "COMITÉ DE AGUA POTABLE RURAL MALLÍN DEL TREILE",
    "connections": 68,
    "beneficiaries": 210,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002496",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUILMAHUE",
    "connections": 168,
    "beneficiaries": 520,
    "province": "MALLECO",
    "commune": "LONQUIMAY",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000016",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA TRINTRE",
    "connections": 150,
    "beneficiaries": 465,
    "province": "MALLECO",
    "commune": "LOS SAUCES",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000020",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PICHIPELLAHUÉN",
    "connections": 72,
    "beneficiaries": 223,
    "province": "MALLECO",
    "commune": "LUMACO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000096",
    "name": "COMITÉ DE AGUA POTABLE RURAL LOS MORROS",
    "connections": 225,
    "beneficiaries": 697,
    "province": "MALLECO",
    "commune": "LUMACO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000018",
    "name": "COMITÉ DE AGUA POTABLE RURAL SECTOR HUEICO",
    "connections": 92,
    "beneficiaries": 285,
    "province": "MALLECO",
    "commune": "LUMACO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000019",
    "name": "COMITÉ DE AGUA POTABLE RURAL SECTOR PANTANO",
    "connections": 41,
    "beneficiaries": 127,
    "province": "MALLECO",
    "commune": "LUMACO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003024",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL ESCORIAL",
    "connections": 88,
    "beneficiaries": 272,
    "province": "CAUTÍN",
    "commune": "MELIPEUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000870",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL MEMBRILLO",
    "connections": 177,
    "beneficiaries": 548,
    "province": "CAUTÍN",
    "commune": "MELIPEUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000844",
    "name": "COMITÉ DE AGUA POTABLE RURAL SANTA MARÍA DE LLAIMA",
    "connections": 236,
    "beneficiaries": 731,
    "province": "CAUTÍN",
    "commune": "MELIPEUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000871",
    "name": "COOPERATIVA DE SERVICIOS DE ABASTECIMIENTO Y DISTRIBUCIÓN DE AGUA POTABLE, ALCANTARILLADO Y SANEAMIENTO AMBIENTAL AG. MELIPEUCO LTDA.",
    "connections": 1600,
    "beneficiaries": 4960,
    "province": "CAUTÍN",
    "commune": "MELIPEUCO",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002155",
    "name": "COMITÉ DE AGUA POTABLE RURAL ALTO BOROA",
    "connections": 149,
    "beneficiaries": 461,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000874",
    "name": "COMITÉ DE AGUA POTABLE RURAL BOLILCHE",
    "connections": 108,
    "beneficiaries": 334,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000876",
    "name": "COMITÉ DE AGUA POTABLE RURAL CANCURA",
    "connections": 112,
    "beneficiaries": 347,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000877",
    "name": "COMITÉ DE AGUA POTABLE RURAL CARDAL",
    "connections": 107,
    "beneficiaries": 331,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002160",
    "name": "COMITÉ DE AGUA POTABLE RURAL CUSACO",
    "connections": 437,
    "beneficiaries": 1354,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000879",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE ENTRE RÍOS",
    "connections": 243,
    "beneficiaries": 753,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000880",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE TRANAMIL PICHÚN RULO",
    "connections": 185,
    "beneficiaries": 573,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000873",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA ALMAGRO",
    "connections": 220,
    "beneficiaries": 682,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000878",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL PERAL",
    "connections": 125,
    "beneficiaries": 387,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000875",
    "name": "COMITÉ DE AGUA POTABLE RURAL ESTACIÓN BOROA",
    "connections": 267,
    "beneficiaries": 827,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000881",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUALACURA",
    "connections": 113,
    "beneficiaries": 350,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000883",
    "name": "COMITÉ DE AGUA POTABLE RURAL LUMAHUE",
    "connections": 100,
    "beneficiaries": 310,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002473",
    "name": "COMITÉ DE AGUA POTABLE RURAL MISIÓN BOROA",
    "connections": 435,
    "beneficiaries": 1348,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000807",
    "name": "COMITÉ DE AGUA POTABLE RURAL MOLCO BAJO UNIDO",
    "connections": 130,
    "beneficiaries": 403,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002472",
    "name": "COMITÉ DE AGUA POTABLE RURAL PILLUMALLÍN",
    "connections": 437,
    "beneficiaries": 1354,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003033",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUENTE NEGRO",
    "connections": 188,
    "beneficiaries": 582,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000882",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUECHU-MAPU",
    "connections": 311,
    "beneficiaries": 964,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003034",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUEUPUE, COIHUE Y LLANCÁN",
    "connections": 162,
    "beneficiaries": 502,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000939",
    "name": "COMITÉ DE AGUA POTABLE RURAL RENGALIL",
    "connections": 555,
    "beneficiaries": 1720,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000884",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRAITRAICO",
    "connections": 418,
    "beneficiaries": 1295,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000885",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRIHUECHE",
    "connections": 150,
    "beneficiaries": 465,
    "province": "CAUTÍN",
    "commune": "NUEVA IMPERIAL",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002157",
    "name": "COMITÉ DE AGUA POTABLE RURAL CHAMPULLI",
    "connections": 238,
    "beneficiaries": 737,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002478",
    "name": "COMITÉ DE AGUA POTABLE RURAL COLPANAO ZANJA MAQUEHUE",
    "connections": 299,
    "beneficiaries": 926,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002158",
    "name": "COMITÉ DE AGUA POTABLE RURAL COMUNIDAD VALENTÍN CALVUIN",
    "connections": 137,
    "beneficiaries": 424,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000890",
    "name": "COMITÉ DE AGUA POTABLE RURAL CURRIHUIL SANDOVAL",
    "connections": 294,
    "beneficiaries": 911,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000894",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE METRENCO",
    "connections": 427,
    "beneficiaries": 1323,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000839",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PRADO HUICHAHUE",
    "connections": 107,
    "beneficiaries": 331,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003022",
    "name": "COMITÉ DE AGUA POTABLE RURAL DEHUEPILLE",
    "connections": 444,
    "beneficiaries": 1376,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000898",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUALAHUE",
    "connections": 240,
    "beneficiaries": 744,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000899",
    "name": "COMITÉ DE AGUA POTABLE RURAL ILLAF ESPERANZA",
    "connections": 911,
    "beneficiaries": 2824,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000893",
    "name": "COMITÉ DE AGUA POTABLE RURAL LICANCO GRANDE",
    "connections": 247,
    "beneficiaries": 765,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000901",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLAMAICO PUCULFEN",
    "connections": 474,
    "beneficiaries": 1469,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000891",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLEUVUL SANDOVAL CONUN HUENU",
    "connections": 118,
    "beneficiaries": 365,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000895",
    "name": "COMITÉ DE AGUA POTABLE RURAL MILLAHUÍN",
    "connections": 218,
    "beneficiaries": 675,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002981",
    "name": "COMITÉ DE AGUA POTABLE RURAL NEWEN COYAHUE",
    "connections": 92,
    "beneficiaries": 285,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002168",
    "name": "COMITÉ DE AGUA POTABLE RURAL PILPILCO",
    "connections": 166,
    "beneficiaries": 514,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000097",
    "name": "COMITÉ DE AGUA POTABLE RURAL PITRELAHUE",
    "connections": 265,
    "beneficiaries": 821,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002165",
    "name": "COMITÉ DE AGUA POTABLE RURAL PRADO PUELLO",
    "connections": 180,
    "beneficiaries": 558,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000897",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUENTE QUEPE",
    "connections": 340,
    "beneficiaries": 1054,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000896",
    "name": "COMITÉ DE AGUA POTABLE RURAL REMOLINO MAQUEHUE",
    "connections": 140,
    "beneficiaries": 434,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000841",
    "name": "COMITÉ DE AGUA POTABLE RURAL SAN RAMÓN",
    "connections": 408,
    "beneficiaries": 1264,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002477",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRUF TRUF LAS MINAS",
    "connections": 144,
    "beneficiaries": 446,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003301",
    "name": "COMITÉ DE AGUA POTABLE YAUYAGUEN",
    "connections": 328,
    "beneficiaries": 1016,
    "province": "CAUTÍN",
    "commune": "PADRE LAS CASAS",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000905",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE MILLALÉN ZAPATA DE PERQUENCO",
    "connections": 107,
    "beneficiaries": 331,
    "province": "CAUTÍN",
    "commune": "PERQUENCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000904",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE QUILLEM",
    "connections": 82,
    "beneficiaries": 254,
    "province": "CAUTÍN",
    "commune": "PERQUENCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003304",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL SOL DE PERQUENCO",
    "connections": 112,
    "beneficiaries": 347,
    "province": "CAUTÍN",
    "commune": "PERQUENCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000906",
    "name": "COMITÉ DE AGUA POTABLE RURAL FERNANDO CARILAO",
    "connections": 103,
    "beneficiaries": 319,
    "province": "CAUTÍN",
    "commune": "PERQUENCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000902",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUALLEPENCO",
    "connections": 297,
    "beneficiaries": 920,
    "province": "CAUTÍN",
    "commune": "PERQUENCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002481",
    "name": "COMITÉ DE AGUA POTABLE RURAL CHANCO",
    "connections": 130,
    "beneficiaries": 403,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003055",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE BAJADA DE PIEDRA",
    "connections": 202,
    "beneficiaries": 626,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000907",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CARILAFQUÉN",
    "connections": 135,
    "beneficiaries": 418,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000908",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE COMUY",
    "connections": 164,
    "beneficiaries": 508,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000909",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE FAJA MAISAN",
    "connections": 97,
    "beneficiaries": 300,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000976",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE LA CASCADA",
    "connections": 45,
    "beneficiaries": 139,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000911",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE LOS GALPONES",
    "connections": 149,
    "beneficiaries": 461,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000912",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE MAHUIDANCHE",
    "connections": 102,
    "beneficiaries": 316,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000914",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE QUINQUE",
    "connections": 176,
    "beneficiaries": 545,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000917",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE RESERVA RAIN MAHUIDANCHE",
    "connections": 240,
    "beneficiaries": 744,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000915",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE TIL TIL",
    "connections": 104,
    "beneficiaries": 322,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000910",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL ESFUERZO PULÓN LOICA",
    "connections": 109,
    "beneficiaries": 337,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002159",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUALLIZADA CHADA MOLCO",
    "connections": 246,
    "beneficiaries": 762,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002480",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUEFEL CANTARRANA",
    "connections": 219,
    "beneficiaries": 678,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002142",
    "name": "COMITÉ DE AGUA POTABLE RURAL MILLAHUIN BAJO",
    "connections": 446,
    "beneficiaries": 1382,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000954",
    "name": "COMITÉ DE AGUA POTABLE RURAL NIRRIPIL Y SANTA AMELIA",
    "connections": 132,
    "beneficiaries": 409,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002141",
    "name": "COMITÉ DE AGUA POTABLE RURAL POLUL",
    "connections": 288,
    "beneficiaries": 892,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000913",
    "name": "COMITÉ DE AGUA POTABLE RURAL PURAQUINA ALTO",
    "connections": 151,
    "beneficiaries": 468,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002479",
    "name": "COMITÉ DE AGUA POTABLE RURAL PURAQUINA BAJO",
    "connections": 63,
    "beneficiaries": 195,
    "province": "CAUTÍN",
    "commune": "PITRUFQUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000918",
    "name": "COMITÉ DE AGUA POTABLE RURAL CABURGUA BAJO",
    "connections": 1207,
    "beneficiaries": 3741,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002123",
    "name": "COMITÉ DE AGUA POTABLE RURAL CARILEUFÚ",
    "connections": 235,
    "beneficiaries": 728,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000919",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CARHUELLO",
    "connections": 333,
    "beneficiaries": 1032,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000921",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PALGUIN BAJO",
    "connections": 103,
    "beneficiaries": 319,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000927",
    "name": "COMITÉ DE AGUA POTABLE RURAL LA BARDA",
    "connections": 148,
    "beneficiaries": 458,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002124",
    "name": "COMITÉ DE AGUA POTABLE RURAL METREÑEHUE",
    "connections": 154,
    "beneficiaries": 477,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000920",
    "name": "COMITÉ DE AGUA POTABLE RURAL NECULMÁN",
    "connections": 58,
    "beneficiaries": 179,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000922",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUELHUE",
    "connections": 140,
    "beneficiaries": 434,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000923",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUETROLEUFU",
    "connections": 720,
    "beneficiaries": 2232,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000924",
    "name": "COMITÉ DE AGUA POTABLE RURAL SAN LUIS",
    "connections": 130,
    "beneficiaries": 403,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000925",
    "name": "COMITÉ DE AGUA POTABLE RURAL VILLA SAN PEDRO",
    "connections": 173,
    "beneficiaries": 536,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000926",
    "name": "COMITÉ DE AGUA POTABLE RURAL ZANJÓN SECO",
    "connections": 132,
    "beneficiaries": 409,
    "province": "CAUTÍN",
    "commune": "PUCÓN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000021",
    "name": "COMITÉ DE AGUA POTABLE RURAL BOYECO",
    "connections": 139,
    "beneficiaries": 430,
    "province": "MALLECO",
    "commune": "PURÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000023",
    "name": "COMITÉ DE AGUA POTABLE RURAL COLICURA",
    "connections": 55,
    "beneficiaries": 170,
    "province": "MALLECO",
    "commune": "PURÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000026",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CAUPOLICÁN TRANAMÁN",
    "connections": 416,
    "beneficiaries": 1289,
    "province": "MALLECO",
    "commune": "PURÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000022",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL LINGUE",
    "connections": 31,
    "beneficiaries": 96,
    "province": "MALLECO",
    "commune": "PURÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000024",
    "name": "COMITÉ DE AGUA POTABLE RURAL IPINCO",
    "connections": 95,
    "beneficiaries": 294,
    "province": "MALLECO",
    "commune": "PURÉN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002115",
    "name": "COMITÉ DE AGUA POTABLE RURAL LA ISLA",
    "connections": 84,
    "beneficiaries": 260,
    "province": "MALLECO",
    "commune": "PURÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000027",
    "name": "COMITÉ DE AGUA POTABLE RURAL CASAS BLANCAS",
    "connections": 32,
    "beneficiaries": 99,
    "province": "MALLECO",
    "commune": "RENAICO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000028",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE HUELEHUEICO",
    "connections": 113,
    "beneficiaries": 350,
    "province": "MALLECO",
    "commune": "RENAICO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000030",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE TIJERAL",
    "connections": 873,
    "beneficiaries": 2706,
    "province": "MALLECO",
    "commune": "RENAICO",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000029",
    "name": "COMITÉ DE AGUA POTABLE RURAL MANZANARES",
    "connections": 110,
    "beneficiaries": 341,
    "province": "MALLECO",
    "commune": "RENAICO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003015",
    "name": "COMITÉ DE AGUA POTABLE RURAL ALMA CUDILEUFU",
    "connections": 95,
    "beneficiaries": 294,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000928",
    "name": "COMITÉ DE AGUA POTABLE RURAL BOCA BUDI",
    "connections": 100,
    "beneficiaries": 310,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000930",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PUERTO DOMÍNGUEZ",
    "connections": 222,
    "beneficiaries": 688,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003023",
    "name": "COMITÉ DE AGUA POTABLE RURAL DOLLINCO LLARQUENCO",
    "connections": 144,
    "beneficiaries": 446,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000931",
    "name": "COMITÉ DE AGUA POTABLE RURAL EL TEMO",
    "connections": 84,
    "beneficiaries": 260,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002483",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUAPI BUDI",
    "connections": 91,
    "beneficiaries": 282,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003026",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLAGUEY QUIFO",
    "connections": 150,
    "beneficiaries": 465,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002482",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLANGUI",
    "connections": 78,
    "beneficiaries": 241,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003028",
    "name": "COMITÉ DE AGUA POTABLE RURAL MILLAHUECO ROLONCHE",
    "connections": 166,
    "beneficiaries": 514,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003030",
    "name": "COMITÉ DE AGUA POTABLE RURAL NAUPE",
    "connections": 204,
    "beneficiaries": 632,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000929",
    "name": "COMITÉ DE AGUA POTABLE RURAL OÑOICO",
    "connections": 50,
    "beneficiaries": 155,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002144",
    "name": "COMITÉ DE AGUA POTABLE RURAL PELECO TRES ESQUINAS",
    "connections": 155,
    "beneficiaries": 480,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003032",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUAUCHO",
    "connections": 214,
    "beneficiaries": 663,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002145",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUECHOCAHUÍN BAJO",
    "connections": 138,
    "beneficiaries": 427,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000932",
    "name": "COMITÉ DE AGUA POTABLE RURAL SECTOR ALMA GUACOLDA",
    "connections": 165,
    "beneficiaries": 511,
    "province": "CAUTÍN",
    "commune": "SAAVEDRA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000933",
    "name": "COMITÉ DE AGUA POTABLE RURAL BOTROLHUE",
    "connections": 216,
    "beneficiaries": 669,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000934",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CONOCO GRANDE",
    "connections": 72,
    "beneficiaries": 223,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000942",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE LIRCAY",
    "connections": 215,
    "beneficiaries": 666,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000936",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE MOLLULCO",
    "connections": 253,
    "beneficiaries": 784,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000937",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE MONTE VERDE",
    "connections": 180,
    "beneficiaries": 558,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000940",
    "name": "COMITÉ DE AGUA POTABLE RURAL HUECHE HUENULAF",
    "connections": 158,
    "beneficiaries": 489,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000941",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLADQUIHUE",
    "connections": 377,
    "beneficiaries": 1168,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000935",
    "name": "COMITÉ DE AGUA POTABLE RURAL MAÑIO",
    "connections": 520,
    "beneficiaries": 1612,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003031",
    "name": "COMITÉ DE AGUA POTABLE RURAL PAILLAO MAPU TROMENMALLIN",
    "connections": 431,
    "beneficiaries": 1336,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000938",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRAÑI TRAÑI",
    "connections": 197,
    "beneficiaries": 610,
    "province": "CAUTÍN",
    "commune": "TEMUCO",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000943",
    "name": "COMITÉ DE AGUA POTABLE RURAL ALTO CHELLE BAJO",
    "connections": 45,
    "beneficiaries": 139,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000944",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE BARROS ARANA",
    "connections": 466,
    "beneficiaries": 1444,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000945",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE HUALPÍN",
    "connections": 1200,
    "beneficiaries": 3720,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002132",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE HUENTE",
    "connections": 220,
    "beneficiaries": 682,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000946",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE HUILIO REHUELHUE",
    "connections": 194,
    "beneficiaries": 601,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000948",
    "name": "COMITÉ DE AGUA POTABLE RURAL ENTRE RÍOS LLOLLINCO",
    "connections": 176,
    "beneficiaries": 545,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002487",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLOLLELHUE ALTO Y BAJO",
    "connections": 109,
    "beneficiaries": 337,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002486",
    "name": "COMITÉ DE AGUA POTABLE RURAL LUMAHUE-ALLIPÉN-LLAGUEPULLI",
    "connections": 220,
    "beneficiaries": 682,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002485",
    "name": "COMITÉ DE AGUA POTABLE RURAL MALAHUE",
    "connections": 115,
    "beneficiaries": 356,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003029",
    "name": "COMITÉ DE AGUA POTABLE RURAL MOLONHUE",
    "connections": 94,
    "beneficiaries": 291,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002135",
    "name": "COMITÉ DE AGUA POTABLE RURAL NEICUF POCULÓN, TEODORO SCHMIDT Y SALTA PURA",
    "connections": 563,
    "beneficiaries": 1745,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002484",
    "name": "COMITÉ DE AGUA POTABLE RURAL PEÑEHUE",
    "connections": 250,
    "beneficiaries": 775,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000947",
    "name": "COMITÉ DE AGUA POTABLE RURAL Y ALCANTARILLADO DE TEODORO SCHMIDT",
    "connections": 1420,
    "beneficiaries": 4402,
    "province": "CAUTÍN",
    "commune": "TEODORO SCHMIDT",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000951",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE NUEVA QUEULE",
    "connections": 730,
    "beneficiaries": 2263,
    "province": "CAUTÍN",
    "commune": "TOLTÉN",
    "classification": "MAYOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000952",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA LOS BOLDOS",
    "connections": 312,
    "beneficiaries": 967,
    "province": "CAUTÍN",
    "commune": "TOLTÉN",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000953",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA O'HIGGINS",
    "connections": 65,
    "beneficiaries": 201,
    "province": "CAUTÍN",
    "commune": "TOLTÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000949",
    "name": "COMITÉ DE AGUA POTABLE RURAL LAS VERTIENTES",
    "connections": 350,
    "beneficiaries": 1085,
    "province": "CAUTÍN",
    "commune": "TOLTÉN",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002488",
    "name": "COMITÉ DE AGUA POTABLE RURAL LEUFU LAFQUEN DESDE EL TROMEN HASTA ISLA",
    "connections": 726,
    "beneficiaries": 2250,
    "province": "CAUTÍN",
    "commune": "TOLTÉN",
    "classification": "MAYOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002111",
    "name": "COMITÉ DE AGUA POTABLE RURAL COMUNIDAD CONTRERAS",
    "connections": 157,
    "beneficiaries": 486,
    "province": "MALLECO",
    "commune": "TRAIGUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000017",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA QUILQUÉN",
    "connections": 50,
    "beneficiaries": 155,
    "province": "MALLECO",
    "commune": "TRAIGUÉN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000032",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CALIFORNIA",
    "connections": 44,
    "beneficiaries": 136,
    "province": "MALLECO",
    "commune": "VICTORIA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003053",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PELON MAPU",
    "connections": 225,
    "beneficiaries": 697,
    "province": "MALLECO",
    "commune": "VICTORIA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000033",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE PÚA",
    "connections": 292,
    "beneficiaries": 905,
    "province": "MALLECO",
    "commune": "VICTORIA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000034",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE QUINO",
    "connections": 234,
    "beneficiaries": 725,
    "province": "MALLECO",
    "commune": "VICTORIA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000036",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VILLA CAUTÍN",
    "connections": 32,
    "beneficiaries": 99,
    "province": "MALLECO",
    "commune": "VICTORIA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000035",
    "name": "COMITÉ DE AGUA POTABLE RURAL RUAL DE SELVA OSCURA",
    "connections": 400,
    "beneficiaries": 1240,
    "province": "MALLECO",
    "commune": "VICTORIA",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000956",
    "name": "COMITÉ DE AGUA POTABLE RURAL CODINHUE",
    "connections": 271,
    "beneficiaries": 840,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002174",
    "name": "COMITÉ DE AGUA POTABLE RURAL COIHUECO",
    "connections": 107,
    "beneficiaries": 331,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000963",
    "name": "COMITÉ DE AGUA POTABLE RURAL CRUZ DEL SUR",
    "connections": 79,
    "beneficiaries": 244,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003021",
    "name": "COMITÉ DE AGUA POTABLE RURAL CURACO MALLA STA. ISABEL EL MIRADOR",
    "connections": 470,
    "beneficiaries": 1457,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000955",
    "name": "COMITÉ DE AGUA POTABLE RURAL CURILEO",
    "connections": 195,
    "beneficiaries": 604,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000958",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE GENERAL LÓPEZ",
    "connections": 369,
    "beneficiaries": 1143,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000961",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE SAN PATRICIO",
    "connections": 620,
    "beneficiaries": 1922,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000962",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE SANTA MARÍA DE QUEPE",
    "connections": 8,
    "beneficiaries": 24,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000959",
    "name": "COMITÉ DE AGUA POTABLE RURAL LA VICTORIA ALTA",
    "connections": 114,
    "beneficiaries": 353,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000957",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLAIMA EL CRUCERO",
    "connections": 29,
    "beneficiaries": 89,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002490",
    "name": "COMITÉ DE AGUA POTABLE RURAL LONCOCHE CHICO",
    "connections": 146,
    "beneficiaries": 452,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002489",
    "name": "COMITÉ DE AGUA POTABLE RURAL QUINTRILPE",
    "connections": 250,
    "beneficiaries": 775,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000960",
    "name": "COMITÉ DE AGUA POTABLE RURAL SANTUARIO PIRCUNCHE",
    "connections": 250,
    "beneficiaries": 775,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003054",
    "name": "COMITÉ DE AGUA POTABLE RURAL TRAWUNKO DE VEGA REDONDA",
    "connections": 521,
    "beneficiaries": 1615,
    "province": "CAUTÍN",
    "commune": "VILCÚN",
    "classification": "MEDIANO",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003310",
    "name": "COMITÉ AGUA POTABLE RURAL MOLCO MEDIO",
    "connections": 141,
    "beneficiaries": 437,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000966",
    "name": "COMITÉ DE AGUA POTABLE RURAL CHUCAUCO ELTUME",
    "connections": 294,
    "beneficiaries": 911,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003020",
    "name": "COMITÉ DE AGUA POTABLE RURAL CUDICO ALTO Y BAJO",
    "connections": 404,
    "beneficiaries": 1252,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000965",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CATRICO LOS ULMOS",
    "connections": 126,
    "beneficiaries": 390,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000978",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE CHEILLACO",
    "connections": 185,
    "beneficiaries": 573,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000979",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE EL SAUCE",
    "connections": 168,
    "beneficiaries": 520,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000972",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE NANCUL",
    "connections": 669,
    "beneficiaries": 2073,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MAYOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000974",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE SANTA FILOMENA PEDREGOSO",
    "connections": 169,
    "beneficiaries": 523,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000975",
    "name": "COMITÉ DE AGUA POTABLE RURAL DE VIDA NUEVA",
    "connections": 133,
    "beneficiaries": 412,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002492",
    "name": "COMITÉ DE AGUA POTABLE RURAL LIUMALLA SUR",
    "connections": 118,
    "beneficiaries": 365,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000969",
    "name": "COMITÉ DE AGUA POTABLE RURAL LLAU LLAU",
    "connections": 402,
    "beneficiaries": 1246,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000970",
    "name": "COMITÉ DE AGUA POTABLE RURAL LONCOTRARO",
    "connections": 142,
    "beneficiaries": 440,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000967",
    "name": "COMITÉ DE AGUA POTABLE RURAL LOS GUINDOS",
    "connections": 177,
    "beneficiaries": 548,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003311",
    "name": "COMITÉ DE AGUA POTABLE RURAL MALLOCO LOLENCO",
    "connections": 293,
    "beneficiaries": 908,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000968",
    "name": "COMITÉ DE AGUA POTABLE RURAL MOLCO ALTO",
    "connections": 170,
    "beneficiaries": 527,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000971",
    "name": "COMITÉ DE AGUA POTABLE RURAL MOLCO-BAJO",
    "connections": 415,
    "beneficiaries": 1286,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000977",
    "name": "COMITÉ DE AGUA POTABLE RURAL PICHILEUFU COLLICO LIUMALLA",
    "connections": 81,
    "beneficiaries": 251,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002491",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUTABLA",
    "connections": 365,
    "beneficiaries": 1131,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR000973",
    "name": "COMITÉ DE AGUA POTABLE RURAL PUTUE",
    "connections": 150,
    "beneficiaries": 465,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  },
  {
    "code": "SSR003312",
    "name": "COMITÉ DE AGUA POTABLE RURAL VOIPIR",
    "connections": 446,
    "beneficiaries": 1382,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MEDIANO",
    "generator": "SI",
    "telemetry": "S/I"
  },
  {
    "code": "SSR002122",
    "name": "COMITÉ DE CHAURA WITRA KOANIN (TIRAR AGUA)",
    "connections": 128,
    "beneficiaries": 396,
    "province": "CAUTÍN",
    "commune": "VILLARRICA",
    "classification": "MENOR",
    "generator": "NO",
    "telemetry": "S/I"
  }
];

